import React, { useEffect, useState } from 'react';
import { CheckCircle, XCircle, Clock, Activity, AlertTriangle, FileText } from 'lucide-react';

interface TestReport {
  lastRun: string;
  status: 'SUCCESS' | 'FAILED' | 'PENDING';
  steps: {
    [key: string]: {
      status: 'SUCCESS' | 'FAILED' | 'PENDING';
      message: string;
    }
  };
  errors: string[];
}

export const AutomationDashboard: React.FC = () => {
  const [report, setReport] = useState<TestReport | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchReport = async () => {
    try {
      // In a real deployed environment, this file is generated by the node script
      // and served statically from the public folder.
      const res = await fetch('/automation_status.json');
      if (res.ok) {
        const data = await res.json();
        setReport(data);
      }
    } catch (e) {
      console.error("Could not load automation report", e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReport();
    const interval = setInterval(fetchReport, 5000); // Poll every 5s
    return () => clearInterval(interval);
  }, []);

  if (loading) return <div className="p-8 text-center font-mono text-gray-500">Loading diagnostics...</div>;

  if (!report) {
    return (
      <div className="bg-gray-900 border border-gray-800 rounded-xl p-8 text-center">
        <AlertTriangle className="w-12 h-12 text-yellow-500 mx-auto mb-4" />
        <h3 className="text-xl font-bold text-gray-200">No Test Data Found</h3>
        <p className="text-gray-500 mt-2">Run <code>npm run test:batch</code> to generate a diagnostic report.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="bg-[#161616] border border-gray-800 rounded-xl p-6">
        <div className="flex justify-between items-center mb-6">
          <div>
            <h2 className="text-2xl font-bold text-white flex items-center gap-2">
              <Activity className="w-6 h-6 text-indigo-400" />
              Automation Diagnostics
            </h2>
            <p className="text-sm text-gray-500 font-mono mt-1">
              Last Run: {new Date(report.lastRun).toLocaleString()}
            </p>
          </div>
          <div className={`px-4 py-2 rounded-full border font-mono font-bold flex items-center gap-2 ${
            report.status === 'SUCCESS' 
              ? 'bg-green-900/30 text-green-400 border-green-800' 
              : 'bg-red-900/30 text-red-400 border-red-800'
          }`}>
            {report.status === 'SUCCESS' ? <CheckCircle className="w-5 h-5" /> : <XCircle className="w-5 h-5" />}
            {report.status}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {Object.entries(report.steps).map(([key, step]) => (
            <div key={key} className="bg-black/50 border border-gray-800 p-4 rounded-lg">
              <div className="flex justify-between items-start mb-2">
                <span className="text-sm font-mono text-gray-400 uppercase">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
                {step.status === 'SUCCESS' 
                  ? <CheckCircle className="w-4 h-4 text-green-500" /> 
                  : <XCircle className="w-4 h-4 text-red-500" />
                }
              </div>
              <p className="text-sm text-gray-200">{step.message || 'No details provided'}</p>
            </div>
          ))}
        </div>

        {report.errors.length > 0 && (
          <div className="mt-6 bg-red-900/10 border border-red-900/50 p-4 rounded-lg">
            <h4 className="text-red-400 font-bold mb-2 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4" /> Errors Detected
            </h4>
            <ul className="list-disc list-inside text-sm text-red-300 font-mono">
              {report.errors.map((err, idx) => (
                <li key={idx}>{err}</li>
              ))}
            </ul>
          </div>
        )}
      </div>

      <div className="bg-[#161616] border border-gray-800 rounded-xl p-6">
         <h3 className="text-lg font-bold text-white flex items-center gap-2 mb-4">
            <FileText className="w-5 h-5 text-gray-400" />
            Git Automation Configuration
         </h3>
         <div className="bg-black p-4 rounded border border-gray-800 font-mono text-xs text-gray-400 overflow-x-auto">
            <p className="mb-2 text-indigo-400"># To enable auto-push, configure your environment:</p>
            <p className="mb-4">
              # Option 1: SSH (Recommended)<br/>
              ssh-keygen -t ed25519 -C "bot@securityfeed.ai"<br/>
              # Add public key to GitHub Repo Settings > Deploy Keys
            </p>
            <p>
              # Option 2: HTTPS Token (Set remote URL manually)<br/>
              git remote set-url origin https://[TOKEN]@github.com/[USER]/[REPO].git
            </p>
         </div>
      </div>
    </div>
  );
};